// GENERATED CODE - DO NOT MODIFY BY HAND
// dart format width=80

// **************************************************************************
// BindxGenerator
// **************************************************************************

// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by BindxGenerator

part of 'api_store.dart';

extension ApiStoreBindx on ApiStore {
  /// Concurrent wrapper for fetchData
  Future<String> fetchDataConcurrent(String endpoint) async {
    return await executeConcurrent(
      () => this.fetchData(endpoint),
      annotation: _fetchDataConcurrentConfig,
    );
  }

  static const _fetchDataConcurrentConfig = Concurrent(
    maxConcurrent: 3,
    queueKey: 'api_calls',
    priority: 5,
    debounce: true,
    debounceDuration: Duration(milliseconds: 300),
  );

  /// Concurrent wrapper for throttledApiCall
  Future<void> throttledApiCallConcurrent() async {
    return await executeConcurrent(
      () => this.throttledApiCall(),
      annotation: _throttledApiCallConcurrentConfig,
    );
  }

  static const _throttledApiCallConcurrentConfig = Concurrent(
    throttle: true,
    throttleDuration: Duration(milliseconds: 300),
  );

  /// Concurrent wrapper for complexApiCall
  Future<String> complexApiCallConcurrent(String endpoint) async {
    return await executeConcurrent(
      () => this.complexApiCall(endpoint),
      annotation: _complexApiCallConcurrentConfig,
    );
  }

  static const _complexApiCallConcurrentConfig = Concurrent(maxConcurrent: 2);

  /// Retry wrapper for fetchWithRetry
  Future<Map<String, dynamic>> fetchWithRetryWithRetry(String url) async {
    int attempts = 0;
    while (attempts < 5) {
      try {
        return await this.fetchWithRetry(url);
      } catch (e) {
        attempts++;
        if (attempts >= 5) rethrow;
        await Future.delayed(Duration(seconds: 1));
      }
    }
    throw Exception('Max retry attempts reached');
  }

  /// Retry wrapper for complexApiCall
  Future<String> complexApiCallWithRetry(String endpoint) async {
    int attempts = 0;
    while (attempts < 3) {
      try {
        return await this.complexApiCall(endpoint);
      } catch (e) {
        attempts++;
        if (attempts >= 3) rethrow;
        await Future.delayed(Duration(seconds: 1));
      }
    }
    throw Exception('Max retry attempts reached');
  }

  /// Timeout wrapper for slowEndpoint
  Future<String> slowEndpointWithTimeout() async {
    return await this.slowEndpoint().timeout(
      Duration(seconds: 30),
      onTimeout: () => throw TimeoutException('slowEndpoint timed out'),
    );
  }

  /// Timeout wrapper for complexApiCall
  Future<String> complexApiCallWithTimeout(String endpoint) async {
    return await this
        .complexApiCall(endpoint)
        .timeout(
          Duration(seconds: 30),
          onTimeout: () => throw TimeoutException('complexApiCall timed out'),
        );
  }
}
