// GENERATED CODE - DO NOT MODIFY BY HAND
// dart format width=80

// **************************************************************************
// BindxGenerator
// **************************************************************************

// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by BindxGenerator

part of 'form_store.dart';

extension FormStoreBindx on FormStore {
  /// Concurrent wrapper for submitForm
  Future<bool> submitFormConcurrent() async {
    return await executeConcurrent(
      () => this.submitForm(),
      annotation: _submitFormConcurrentConfig,
    );
  }

  static const _submitFormConcurrentConfig = Concurrent(
    debounce: true,
    debounceDuration: Duration(milliseconds: 300),
  );
}
