// GENERATED CODE - DO NOT MODIFY BY HAND
// dart format width=80

// **************************************************************************
// BindxGenerator
// **************************************************************************

// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by BindxGenerator

part of 'user_store.dart';

extension UserStoreBindx on UserStore {
  /// Concurrent wrapper for updateProfile
  Future<void> updateProfileConcurrent(String name, int age) async {
    return await executeConcurrent(
      () => this.updateProfile(name, age),
      annotation: _updateProfileConcurrentConfig,
    );
  }

  static const _updateProfileConcurrentConfig = Concurrent(
    debounce: true,
    debounceDuration: Duration(milliseconds: 300),
  );

  /// Concurrent wrapper for incrementLoginCount
  Future<void> incrementLoginCountConcurrent() async {
    return await executeConcurrent(
      () => this.incrementLoginCount(),
      annotation: _incrementLoginCountConcurrentConfig,
    );
  }

  static const _incrementLoginCountConcurrentConfig = Concurrent(
    maxConcurrent: 3,
    priority: 10,
    throttle: true,
    throttleDuration: Duration(milliseconds: 300),
  );

  /// Retry wrapper for fetchUserData
  Future<Map<String, dynamic>> fetchUserDataWithRetry() async {
    int attempts = 0;
    while (attempts < 3) {
      try {
        return await this.fetchUserData();
      } catch (e) {
        attempts++;
        if (attempts >= 3) rethrow;
        await Future.delayed(Duration(seconds: 1));
      }
    }
    throw Exception('Max retry attempts reached');
  }

  /// Mutex-protected wrapper for criticalUpdate
  Future<void> criticalUpdateLocked(String status) async {
    await acquireLock('userUpdate');
    try {
      return await this.criticalUpdate(status);
    } finally {
      releaseLock('userUpdate');
    }
  }

  /// Timeout wrapper for longRunningTask
  Future<void> longRunningTaskWithTimeout() async {
    return await this.longRunningTask().timeout(
      Duration(seconds: 30),
      onTimeout: () => throw TimeoutException('longRunningTask timed out'),
    );
  }
}
